# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/
resources:
- bases/infrastructure.cluster.x-k8s.io_kvmclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_kvmmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_kvmmachinetemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource
